LibraryMangement/Controllers/AdminController.cs
using LibraryMangement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static System.Collections.Specialized.BitVector32;

namespace LibraryMangement.Controllers
{
    public class AdminController : Controller
    {
        private Library_ManagementEntities adminDb = new Library_ManagementEntities();

        // Returns admin login view, here admin can login.
        [HttpGet]
        [HandleError]
        public ActionResult Login()
        {
            return View();
        }

        // Checks admin credentials, redirecting to admin section (index, tblBooks). 
        [HttpPost]
        [HandleError]
        public ActionResult Login(Admintbl admin)
        {
            Admintbl adm = adminDb.Admintbls.SingleOrDefault(a => a.AdminEmail == admin.AdminEmail && a.AdminPass == admin.AdminPass);
            if (adm != null)
            {
                int id = adm.AdminId;
                Session["adminId"] = adm.AdminId;
                return RedirectToAction("Index", "Booktbl", new { id = id });
            }
            else if (admin.AdminEmail == null && admin.AdminPass == null)
            {
                return View();
            }
            ViewBag.Message = "User name and password are not matching";
            return View();
        }
        /* Admin credentials validation two
        public ActionResult Validate(tblAdmin admin)
        {
            var adm = db.tblAdmins.SingleOrDefault(a => a.AdminEmail == admin.AdminEmail && a.AdminPass == admin.AdminPass);
            if (adm != null)
            {
                int id = adm.AdminId;
                return RedirectToAction("Index", "tblBooks", new { @id = id });
            }
            else if (admin.AdminEmail == null && admin.AdminPass == null)
            {
                return View("Login");
            }
            ViewBag.Message = "User name and password are not matching";
            return View("Login");
        }*/

        // Admin logout, redirect to main. 
        [HandleError]
        public ActionResult Logout()
        {
            Session.Remove("adminId");
            return RedirectToAction("Index", "Home");
        }
    }
}

LibraryMangement/Controllers/AdminTransactionController.cs
using LibraryMangement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LibraryMangement.Controllers
{
    public class AdminTransactionController : Controller
    {
        private Library_ManagementEntities bookDb = new Library_ManagementEntities();
        private Library_ManagementEntities transDb = new Library_ManagementEntities();

        // Returns admin request view, here admin can accept and reject the book requests
        public ActionResult Requests()
        {
            return View(transDb.Transactiontbls.ToList());
        }
        // Returns all book requests in json format.
        public ActionResult GetAllRequests()
        {
            var transactionList = transDb.Transactiontbls.Where(r => r.TranStatus == "Requested").ToList();
            return Json(new { data = transactionList }, JsonRequestBehavior.AllowGet);
        }
        // Accepts the book request.
        public ActionResult AcceptRequest(int? tranId)
        {
            /* try
             {*/
            if (tranId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transactiontbl transaction = transDb.Transactiontbls.FirstOrDefault(t => t.TransactionId == tranId);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            transaction.TranStatus = "Accepted";
            transaction.TransactionDate = DateTime.Now.ToShortDateString();
            transDb.SaveChanges();
            return View("Requests");
            /*}
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }*/

        }
        // Reject the book request. 
        public ActionResult RejectRequest(int? tranId)
        {
            /*try
            {*/
            if (tranId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transactiontbl transaction = transDb.Transactiontbls.FirstOrDefault(t => t.TransactionId == tranId);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            transaction.TranStatus = "Rejected";
            transaction.TransactionDate = DateTime.Now.ToShortDateString();
            Booktbl book = bookDb.Booktbls.FirstOrDefault(b => b.BookId == transaction.BookId);
            book.BookCopies = book.BookCopies + 1;
            bookDb.SaveChanges();
            transDb.SaveChanges();
            return View("Requests");
            /*}
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }*/
        }
        // Returns admin accepted view, here admin can view the accepted books.
        public ActionResult Accepted()
        {
            return View(transDb.Transactiontbls.ToList());
        }
        // Returns all accepted books in json format.
        public ActionResult GetAllAccepted()
        {
            var transactionList = transDb.Transactiontbls.Where(r => r.TranStatus == "Accepted").ToList();
            return Json(new { data = transactionList }, JsonRequestBehavior.AllowGet);
        }
        // Returns admin return view, here admin can accept book return requests.
        public ActionResult Return()
        {
            return View(transDb.Transactiontbls.ToList());
        }
        // Returns all return books in json format.
        public ActionResult GetAllReturn()
        {
            var transactionList = transDb.Transactiontbls.Where(r => r.TranStatus == "Returned").ToList();
            return Json(new { data = transactionList }, JsonRequestBehavior.AllowGet);
        }
        // Accepts the book return request.
        public ActionResult AcceptReturn(int? tranId)
        {

            /*try
            {*/
            if (tranId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transactiontbl transaction = transDb.Transactiontbls.FirstOrDefault(t => t.TransactionId == tranId);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            Booktbl book = bookDb.Booktbls.FirstOrDefault(b => b.BookId == transaction.BookId);
            book.BookCopies = book.BookCopies + 1;
            bookDb.SaveChanges();
            transDb.Transactiontbls.Remove(transaction);
            transDb.SaveChanges();
            return View("Return");
            /*}
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }*/
        }
        // Returns admin home view.
        public ActionResult AdminHome()
        {
            return View();
        }
        // Returns admin about view.
        public ActionResult AdminAbout()
        {
            return View();
        }
        // Returns admin contact view.
        public ActionResult AdminContact()
        {
            return View();
        }
    }
}

LibraryMangement/Controllers/UserController.cs
using LibraryMangement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryMangement.Controllers
{
    public class UserController : Controller
    {
        Library_ManagementEntities userDb = new Library_ManagementEntities();

        // Returns user login view, here admin can login.
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        // Checks user credentials, redirecting to admin section (index, tblBooks). 
        [HttpPost]
        public ActionResult Login(Usertbl user)
        {
            var adm = userDb.Usertbls.SingleOrDefault(a => a.UserEmail == user.UserEmail && a.UserPass == user.UserPass);
            if (adm != null)
            {
                Session["userId"] = adm.UserId;
                Session["userName"] = adm.UserName;
                return RedirectToAction("Index", "Transaction", new { userId = adm.UserId, userName = adm.UserName });
            }
            else if (user.UserEmail == null && user.UserPass == null)
            {
                return View(adm);
            }
            ViewBag.Message = "User name and password are not matching";
            return View();
        }

        /* User credentials validation two
        public ActionResult Validate(tblUser user)
        {
            var adm = db.tblUsers.SingleOrDefault(a => a.UserEmail == user.UserEmail && a.UserPass == user.UserPass);
            if (adm != null)
            {
                Session["userId"] = adm.UserId;
                Session["userName"] = adm.UserName;
                ViewBag.userId= adm.UserId;
                ViewBag.userId = adm.UserId;
                return RedirectToAction("Index", "Borrow", new { userId = adm.UserId, userName = adm.UserName });
            }
               else if (user.UserEmail == null && user.UserPass == null)
            {
                return View("Login");
            }
            ViewBag.Message = "User name and password are not matching";
            return View("Login");
        }
        */

        // User logout, redirect to main. 
        public ActionResult Logout()
        {
            Session.Remove("userId");
            Session.Remove("userName");
            return RedirectToAction("Index", "Home");
        }
    }
}

LibraryMangement/Controllers/UsertblController.cs
using LibraryMangement.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LibraryMangement.Controllers
{
    public class UsertblController : Controller
    {
        private Library_ManagementEntities userDb = new Library_ManagementEntities();

        // GET: tblUsers
        public ActionResult Index()
        {
            return View(userDb.Usertbls.ToList());
        }

        // GET: tblUsers Json
        public ActionResult GetAll()
        {
            var userlist = userDb.Usertbls.ToList();
            return Json(new { data = userlist }, JsonRequestBehavior.AllowGet);
        }

        // GET: tblUsers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usertbl tblUser = userDb.Usertbls.Find(id);
            if (tblUser == null)
            {
                return HttpNotFound();
            }
            return View(tblUser);
        }

        // GET: tblUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: tblUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,UserName,UserGender,UserDep,UserAdminNo,UserEmail,UserPass")] Usertbl tblUser)
        {
            Session.Remove("emailExists");
            if (ModelState.IsValid)
            {

                if (userDb.Usertbls.Where(u => u.UserEmail == tblUser.UserEmail).Count() > 0)
                {
                    Session["emailExists"] = "The Email address is already exists.";
                    return View(tblUser);
                }
                else
                {
                    Session["operationMsg"] = "User added successfully";
                    userDb.Usertbls.Add(tblUser);
                    userDb.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(tblUser);
        }

        // Remove the session datas which are used for alerts
        // OperationAlert
        public ActionResult OperationAlert()
        {
            Session.Remove("operationMsg");
            return RedirectToAction("Index");
        }

        // GET: tblUsers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usertbl tblUser = userDb.Usertbls.Find(id);
            if (tblUser == null)
            {
                return HttpNotFound();
            }
            return View(tblUser);
        }

        // POST: tblUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,UserName,UserGender,UserDep,UserAdminNo,UserEmail,UserPass")] Usertbl tblUser)
        {
            if (ModelState.IsValid)
            {
                Session["operationMsg"] = "User updated successfully";
                userDb.Entry(tblUser).State = EntityState.Modified;
                userDb.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblUser);
        }

        // GET: tblUsers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usertbl tblUser = userDb.Usertbls.Find(id);
            if (tblUser == null)
            {
                return HttpNotFound();
            }
            return View(tblUser);
        }

        // POST: tblUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Usertbl tblUser = userDb.Usertbls.Find(id);
            userDb.Usertbls.Remove(tblUser);
            userDb.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                userDb.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LibraryMangement/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - UrLMS</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/fontawesome-all.css" rel="stylesheet" />
    <link href="~/Content/lmscustom.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body style="padding:unset">
    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-info">
            <span class="icon">
                <i class="fas fa-book-open"></i>
            </span>
            @Html.ActionLink("LibraryMs", "Index", "tblBooks", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item btn-sm btn-info">
                        <i class="fas fa-home"></i>
                        @Html.ActionLink("Home", "AdminHome", "AdminTransaction", new { area = "" }, new { @class = "btn btn-primary btn-lg btn-block" })
                    </li>
                    <li class="nav-item btn-sm btn-info">
                        <i class="fas fa-address-card"></i>
                        @Html.ActionLink("About", "AdminAbout", "AdminTransaction", new { area = "" }, new { @class = "btn btn-primary btn-lg btn-block" })
                    </li>
                    <li class="nav-item btn-sm btn-info">
                        <i class="fas fa-id-badge"></i>
                        @Html.ActionLink("Contact", "AdminContact", "AdminTransaction", new { area = "" }, new { @class = "btn btn-primary btn-lg btn-block" })
                    </li>
                </ul>
                <ul class="navbar-nav justify-content-end" style="padding-right:50px">
                    <li class="" style="padding-left:5px; padding-right:5px">
                        @Html.ActionLink("Books", "Index", "Booktbl", new { area = "" }, new { @class = "btn btn-primary btn-lg btn-block" })
                    </li>
                    <li class="" style="padding-left:5px; padding-right:5px">

                        @Html.ActionLink("Users", "Index", "Usertbl", null, new { @class = "btn btn-primary btn-lg btn-block" })
                    </li>
                    <li class="" style="padding-left: 5px; padding-right: 5px">
                        @Html.ActionLink("Request", "Requests", "AdminTransaction", null, new { @class = "btn btn-primary btn-lg btn-block" })
                    </li>
                    <li class="" style="padding-left:5px; padding-right:5px">
                        @Html.ActionLink("Accepted", "Accepted", "AdminTransaction", null, new { @class = "btn btn-primary btn-lg btn-block" })
                    </li>
                    <li class="" style="padding-left:5px; padding-right:10px">
                        @Html.ActionLink("Return", "Return", "AdminTransaction", null, new { @class = "btn btn-primary btn-lg btn-block" })
                    </li>
                </ul>
                <span class="text-light" style="padding-top:1px; padding-right:15px">Welcome back Admin!!</span>
                <ul class="navbar-nav justify-content-end">
                    <li class="nav-item btn btn-sm btn-danger">
                        <i class="fas fa-sign-out-alt"></i>
                        @Html.ActionLink("Logout", "Logout", "Admin", null, new { @class = "nav-link", onclick = "return alert('Logged out successfully');", style = "display:inline" })
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div style="padding-left:20px; padding-right:20px">
        @RenderBody()
    </div>
    <div>

        <footer>
            <div style="" class="card text-center text-white bg-info">
                <div class="card-header">
                    Thank you for your work
                </div>
               
                <p>&copy; @DateTime.Now.Year - LibraryMs</p>
            </div>
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

LibraryMangement/Views/Shared/UserLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LibraryMs</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/fontawesome-all.css" rel="stylesheet" />
    <link href="~/Content/lmscustom.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body style="padding:unset">
    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-info">
            <span class="icon">
                <i class="fas fa-book-open"></i>
            </span>
            @Html.ActionLink("LibraryMs", "MenuTransaction", "Transaction", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item btn-sm btn-white">
                        <i class="fas fa-home"></i>
                        @Html.ActionLink("Home", "UserHome", "Transaction", null, new { @class = "btn btn-primary btn-lg btn-block" })
                    </li>
                    <li class="nav-item btn-sm btn-white">
                        <i class="fas fa-address-card"></i>
                        @Html.ActionLink("About", "UserAbout", "Transaction", null, new { @class = "btn btn-primary btn-lg btn-block" })
                    </li>
                    <li class="nav-item btn-sm btn-white">
                        <i class="fas fa-id-badge"></i>
                        @Html.ActionLink("Contact", "UserContact", "Transaction", null, new { @class = "btn btn-primary btn-lg btn-block" })
                    </li>
                </ul>
                <ul class="navbar-nav justify-content-end" style="padding-right:50px">
                    <li class="" style="padding-left:5px; padding-right:5px">
                        @Html.ActionLink("Transaction", "MenuTransaction", "Transaction", new { area = "" }, new { @class = "btn btn-primary btn-lg btn-block" })
                    </li>
                    <li class="" style="padding-left:5px; padding-right:5px">

                        @Html.ActionLink("Requested", "MenuRequested", "Transaction", null, new { @class = "btn btn-primary btn-lg btn-block" })
                    </li>
                    <li style="padding-left: 5px; padding-right: 5px ">
                        @Html.ActionLink("Received", "MenuReceived", "Transaction", null, new { @class = "btn btn-primary btn-lg btn-block" })

                    </li>
                    <li class="" style="padding-left:5px; padding-right:10px">
                        @Html.ActionLink("Rejected", "MenuRejected", "Transaction", null, new { @class = "btn btn-primary btn-lg btn-block" })

                    </li>
                </ul>
                <span class="text-black" style="padding-top:1px; padding-right:15px">Welcome back @Session["userName"]!!</span>
                <ul class="navbar-nav justify-content-end">

                    <li class="nav-item btn btn-sm btn-danger">
                        <i class="fas fa-sign-out-alt"></i>
                        @Html.ActionLink("Logout", "Logout", "User", null, new { @class = "btn-red", onclick = "return alert('Logged out successfully');", style = "display:inline" })
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div style="padding-left:20px; padding-right:20px">
        @RenderBody()
    </div>
    <div>

        <footer>
            <div style="" class="card text-center text-White bg-primary">
                <div class="card-header">
                    Thank you for visiting us
                </div>
               
                </div>
                <p>&copy; @DateTime.Now.Year - LibraryMS</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

LibraryMangement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Library Management </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <h2 align="center">Welcome to Simple Library Management System</h2>
    <div class="col">
        <img src="~/Image/Library-MS.jpg" style="width:100%; height:332px; object-fit: cover;"/>
       
    </div>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Library Management", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Login", "Login", "Home")</li>
                    <li>@Html.ActionLink("Feedback", "Index", "Feedback")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>